# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18f16863a418c90e5ab4db4537c072aff6ed749f412f17d7c6cac68d619cdc06e6722610fe83e844b9a74c2c0682e2988e8bf1197a2734a1d7c9f00bc7e25ac7

test:
  secret_key_base: 88a67556dd339875f7d175dbb76f8c504f31062485a0bff988ecc51e8848782cc48932a26644648c226be9fc25647f3438dc5277785aadbfaa22d73245a4947b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
